"""dd file_size column to ile table

Revision ID: 3876f96f7f08
Revises: 
Create Date: 2023-12-15 19:09:19.286004

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3876f96f7f08'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('file', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_size', sa.Float(), nullable=True, server_default='0'))

    # Create a Check Constraint for non-negative file_size
    op.create_check_constraint("non_negative_file_size", "file", "file_size >= 0", schema=None)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['username'])
        batch_op.drop_column('date_joined')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_joined', sa.DATE(), nullable=True))
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('file', schema=None) as batch_op:
        batch_op.drop_constraint("non_negative_file_size", "file", type_='check', schema=None)
        batch_op.drop_column('file_size')

    # ### end Alembic commands ###
